packages:
  - "app/"
  - "studio/"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.8'
  - '@turbo/darwin-arm64@2.10.8'
  - '@turbo/linux-64@2.10.8'
  - '@turbo/linux-arm64@2.10.8'
  - '@turbo/windows-64@2.10.8'
  - '@turbo/windows-arm64@2.10.8'
  - turbo@2.10.8
  - groq@6.13.2
  - '@sanity/access-ui@6.13.2'
  - '@sanity/diff@6.13.2'
  - '@sanity/mutator@6.13.2'
  - '@sanity/schema@6.13.2'
  - '@sanity/types@6.13.2'
  - '@sanity/util@6.13.2'
  - '@sanity/validation@6.13.2'
  - '@sanity/vision@6.13.2'
  - sanity@6.13.2
  - eslint@10.11.0
onlyBuiltDependencies:
  - esbuild
