/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Information = {
	_id: string;
	_type: 'information';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	biography?: Array<
		{
			_key: string;
		} & InternationalizedArrayTextValue
	>;
	impressum?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type Exhibitions = {
	_id: string;
	_type: 'exhibitions';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	type?: 'solo' | 'group';
	title?: string;
	slug?: Slug;
	startDate?: string;
	endDate?: string;
	venue?: {
		name?: string;
		city?: string;
		location?: Geopoint;
	};
	photos?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: Array<
			{
				_key: string;
			} & InternationalizedArrayStringValue
		>;
		caption?: Array<
			{
				_key: string;
			} & InternationalizedArrayStringValue
		>;
		_type: 'image';
		_key: string;
	}>;
	description?: Array<
		{
			_key: string;
		} & InternationalizedArrayTextValue
	>;
};

export type Work = {
	_id: string;
	_type: 'work';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	title?: Array<
		{
			_key: string;
		} & InternationalizedArrayStringValue
	>;
	slug?: Slug;
	date?: string;
	medium?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'medium';
	};
	size?: string;
	description?: Array<
		{
			_key: string;
		} & InternationalizedArrayTextValue
	>;
};

export type Series = {
	_id: string;
	_type: 'series';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: Array<
		{
			_key: string;
		} & InternationalizedArrayStringValue
	>;
	slug?: Slug;
	description?: Array<
		{
			_key: string;
		} & InternationalizedArrayTextValue
	>;
	order?: number;
	works?: Array<{
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: 'work';
	}>;
};

export type Medium = {
	_id: string;
	_type: 'medium';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: Array<
		{
			_key: string;
		} & InternationalizedArrayStringValue
	>;
};

export type InternationalizedArrayTextValue = {
	_type: 'internationalizedArrayTextValue';
	value?: string;
};

export type InternationalizedArrayStringValue = {
	_type: 'internationalizedArrayStringValue';
	value?: string;
};

export type InternationalizedArrayText = Array<
	{
		_key: string;
	} & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
	{
		_key: string;
	} & InternationalizedArrayStringValue
>;

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type AllSanitySchemaTypes =
	| Information
	| Exhibitions
	| Work
	| Series
	| Medium
	| InternationalizedArrayTextValue
	| InternationalizedArrayStringValue
	| InternationalizedArrayText
	| InternationalizedArrayString
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
