/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type WorkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "work";
};

export type Information = {
  _id: string;
  _type: "information";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titleImage?: WorkReference;
  biography?: InternationalizedArrayText;
  impressum?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type InternationalizedArrayText = Array<{
  _key: string;
} & InternationalizedArrayTextValue>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Exhibitions = {
  _id: string;
  _type: "exhibitions";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "solo" | "group";
  title?: string;
  slug?: Slug;
  startDate?: string;
  endDate?: string;
  venue?: {
    name?: string;
    city?: string;
    location?: Geopoint;
  };
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    caption?: InternationalizedArrayString;
    _type: "image";
    _key: string;
  }>;
  description?: InternationalizedArrayText;
};

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type MediumReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "medium";
};

export type Work = {
  _id: string;
  _type: "work";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: InternationalizedArrayString;
  slug?: Slug;
  tags?: Array<{
    _key: string;
  } & TagReference>;
  date?: string;
  medium?: MediumReference;
  size?: string;
};

export type Series = {
  _id: string;
  _type: "series";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  order?: number;
  works?: Array<{
    _key: string;
  } & WorkReference>;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
};

export type Medium = {
  _id: string;
  _type: "medium";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes = WorkReference | Information | InternationalizedArrayText | SanityImageAssetReference | Exhibitions | InternationalizedArrayString | SanityImageCrop | SanityImageHotspot | Geopoint | Slug | TagReference | MediumReference | Work | Series | Tag | Medium | InternationalizedArrayTextValue | InternationalizedArrayStringValue | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset;

// Source: ../app/src/lib/data.remote.ts
// Variable: seriesListQuery
// Query: *[_type == "series"] | order(order desc) {		_id,		slug,		title,		order	}
export type SeriesListQueryResult = Array<{
  _id: string;
  slug: Slug | null;
  title: InternationalizedArrayString | null;
  order: number | null;
}>;

// Source: ../app/src/lib/data.remote.ts
// Variable: seriesBySlugQuery
// Query: *[_type == "series" && slug.current == $slug][0] {		_id,		slug,		title,		order,		works[]-> {			_id,			slug,			title,			image {				...,				asset->{					...,					metadata{						blurHash,						dimensions					}				}			},			date,			size,			medium-> {				_id,				name			}		}	}
export type SeriesBySlugQueryResult = {
  _id: string;
  slug: Slug | null;
  title: InternationalizedArrayString | null;
  order: number | null;
  works: Array<{
    _id: string;
    slug: Slug | null;
    title: InternationalizedArrayString | null;
    image: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    date: string | null;
    size: string | null;
    medium: {
      _id: string;
      name: InternationalizedArrayString | null;
    } | null;
  }> | null;
} | null;

// Source: ../app/src/lib/data.remote.ts
// Variable: worksQuery
// Query: *[_type == "work"] | order(date desc) {		_id,		slug,		title,		image {			...,			asset->{				...,				metadata{					blurHash,					dimensions				}			}		},		date,		size,		tags[]-> {			_id,			name		},		medium-> {			_id,			name		}	}
export type WorksQueryResult = Array<{
  _id: string;
  slug: Slug | null;
  title: InternationalizedArrayString | null;
  image: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  date: string | null;
  size: string | null;
  tags: Array<{
    _id: string;
    name: InternationalizedArrayString | null;
  }> | null;
  medium: {
    _id: string;
    name: InternationalizedArrayString | null;
  } | null;
}>;

// Source: ../app/src/lib/data.remote.ts
// Variable: informationQuery
// Query: *[_type == "information"][0] {		_id,		_type,		titleImage-> {			image {				...,				asset->{					...,					metadata{						blurHash,						dimensions					}				}			}		},		biography,		impressum	}
export type InformationQueryResult = {
  _id: string;
  _type: "information";
  titleImage: {
    image: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  biography: InternationalizedArrayText | null;
  impressum: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../app/src/lib/data.remote.ts
// Variable: seriesSlugsQuery
// Query: *[_type == "series" && defined(slug.current)].slug.current
export type SeriesSlugsQueryResult = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n\t*[_type == \"series\"] | order(order desc) {\n\t\t_id,\n\t\tslug,\n\t\ttitle,\n\t\torder\n\t}\n": SeriesListQueryResult;
    "\n\t*[_type == \"series\" && slug.current == $slug][0] {\n\t\t_id,\n\t\tslug,\n\t\ttitle,\n\t\torder,\n\t\tworks[]-> {\n\t\t\t_id,\n\t\t\tslug,\n\t\t\ttitle,\n\t\t\timage {\n\t\t\t\t...,\n\t\t\t\tasset->{\n\t\t\t\t\t...,\n\t\t\t\t\tmetadata{\n\t\t\t\t\t\tblurHash,\n\t\t\t\t\t\tdimensions\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t},\n\t\t\tdate,\n\t\t\tsize,\n\t\t\tmedium-> {\n\t\t\t\t_id,\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n": SeriesBySlugQueryResult;
    "\n\t*[_type == \"work\"] | order(date desc) {\n\t\t_id,\n\t\tslug,\n\t\ttitle,\n\t\timage {\n\t\t\t...,\n\t\t\tasset->{\n\t\t\t\t...,\n\t\t\t\tmetadata{\n\t\t\t\t\tblurHash,\n\t\t\t\t\tdimensions\n\t\t\t\t}\n\t\t\t}\n\t\t},\n\t\tdate,\n\t\tsize,\n\t\ttags[]-> {\n\t\t\t_id,\n\t\t\tname\n\t\t},\n\t\tmedium-> {\n\t\t\t_id,\n\t\t\tname\n\t\t}\n\t}\n": WorksQueryResult;
    "\n\t*[_type == \"information\"][0] {\n\t\t_id,\n\t\t_type,\n\t\ttitleImage-> {\n\t\t\timage {\n\t\t\t\t...,\n\t\t\t\tasset->{\n\t\t\t\t\t...,\n\t\t\t\t\tmetadata{\n\t\t\t\t\t\tblurHash,\n\t\t\t\t\t\tdimensions\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t},\n\t\tbiography,\n\t\timpressum\n\t}\n": InformationQueryResult;
    "\n\t*[_type == \"series\" && defined(slug.current)].slug.current\n": SeriesSlugsQueryResult;
  }
}

